Experiment_name: ntu_ShiftGCN_joint_xsub

# feeder
feeder: skeleton_dataset.RGB_dataset.Feeder
train_feeder_args:
  skeleton_data_path: D:/RGB_dataset/ETRI/sub/train_data_joint.npy
  skeleton_label_path: D:/RGB_dataset/ETRI/sub/train_label.pkl
  list_file : E:/dataSet/ETRI/16/train.txt
  length : 1
  image_tmpl: "{:05d}.jpg"
  modality: RGB
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  skeleton_data_path: D:/RGB_dataset/ETRI/sub/val_data_joint.npy
  skeleton_label_path: D:/RGB_dataset/ETRI/sub/val_label.pkl
  list_file: E:/dataSet/ETRI/16/val.txt
  length: 1
  image_tmpl: "{:05d}.jpg"


# skeleton_model
skeleton_model: skeleton_model.shift_gcn.Model
model_args:
  output_layers: 'more_layer'
  num_class: 55
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [60, 80, 100]

# training
device: [0]
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 200
nesterov: True
mod: 'skeleton'
phase: 'train'
