Experiment_name: ntu_ShiftGCN_joint_xsub

# feeder
feeder: skeleton_dataset.feeder.Feeder
train_feeder_args:
  data_path: /home/user01/dataSet/etri/skeleton/train_data_joint_motion.npy
  label_path: /home/user01/dataSet/etri/skeleton/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/user01/dataSet/etri/skeleton/val_data_joint_motion.npy
  label_path: /home/user01/dataSet/etri/skeleton/val_label.pkl

# skeleton_model
skeleton_model: skeleton_model.shift_gcn.Model
model_args:
  output_layers : 'avgpool'
  num_class: 55
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [40, 60, 100]

# training
weights: "/home/user01/code/Cross_MARS/ETRI/skeleton/91_0.84.pt"
device: [0]
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 140
nesterov: True
mod: 'skeleton'